export enum OrgRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  EMPLOYEE = 'EMPLOYEE',
  GUEST = 'GUEST',
}

export enum Permission {
  CHAT_CREATE = 'CHAT_CREATE',
  CHAT_DELETE = 'CHAT_DELETE',
  CHAT_MANAGE_MEMBERS = 'CHAT_MANAGE_MEMBERS',
  MESSAGE_DELETE_OWN = 'MESSAGE_DELETE_OWN',
  MESSAGE_DELETE_ANY = 'MESSAGE_DELETE_ANY',
  MESSAGE_EDIT_OWN = 'MESSAGE_EDIT_OWN',
  MESSAGE_PIN = 'MESSAGE_PIN',
  FILE_UPLOAD = 'FILE_UPLOAD',
  FILE_DELETE_OWN = 'FILE_DELETE_OWN',
  FILE_DELETE_ANY = 'FILE_DELETE_ANY',
  TASK_CREATE = 'TASK_CREATE',
  TASK_ASSIGN = 'TASK_ASSIGN',
  TASK_DELETE = 'TASK_DELETE',
  MEMBER_INVITE = 'MEMBER_INVITE',
  MEMBER_REMOVE = 'MEMBER_REMOVE',
  MEMBER_CHANGE_ROLE = 'MEMBER_CHANGE_ROLE',
  ORG_UPDATE = 'ORG_UPDATE',
  ORG_DELETE = 'ORG_DELETE',
  ORG_VIEW_AUDIT = 'ORG_VIEW_AUDIT',
  DEPARTMENT_MANAGE = 'DEPARTMENT_MANAGE',
  CALL_INITIATE = 'CALL_INITIATE',
  CALL_MANAGE = 'CALL_MANAGE',
  CHANNEL_CREATE = 'CHANNEL_CREATE',
  CHANNEL_DELETE = 'CHANNEL_DELETE',
  EXPORT_DATA = 'EXPORT_DATA',
  GUEST_INVITE = 'GUEST_INVITE',
  VIEW_ALL_MEMBERS = 'VIEW_ALL_MEMBERS',
}

export type RolePermissions = Record<OrgRole, Permission[]>;
