"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.STRONG_PASSWORD_REGEX = exports.URL_REGEX = exports.CHANNEL_MENTION_REGEX = exports.MENTION_REGEX = exports.SLUG_REGEX = exports.PHONE_E164_REGEX = exports.EMAIL_REGEX = exports.getFileCategory = exports.ALL_ALLOWED_TYPES = exports.ALLOWED_ARCHIVE_TYPES = exports.ALLOWED_DOCUMENT_TYPES = exports.ALLOWED_AUDIO_TYPES = exports.ALLOWED_VIDEO_TYPES = exports.ALLOWED_IMAGE_TYPES = exports.WS_EVENTS = exports.REFRESH_TOKEN_MAX_SESSIONS = exports.INVITE_EXPIRY_HOURS = exports.PRESENCE_OFFLINE_THRESHOLD_MS = exports.TYPING_INDICATOR_TIMEOUT_MS = exports.MESSAGE_EDIT_WINDOW_MS = exports.MAX_TASK_WATCHERS = exports.MAX_FILE_ATTACHMENTS_PER_MESSAGE = exports.MAX_PINNED_MESSAGES = exports.MAX_REACTIONS_PER_MESSAGE = exports.MAX_SEARCH_RESULTS = exports.MAX_MESSAGES_PER_PAGE = exports.MAX_CHATS_PER_PAGE = exports.MAX_ORGS_PER_USER = exports.MAX_CHANNEL_MEMBERS = exports.MAX_GROUP_MEMBERS = exports.MAX_FILE_SIZE_GUEST_BYTES = exports.MAX_FILE_SIZE_BYTES = exports.MAX_MESSAGE_LENGTH = exports.ROLE_HIERARCHY = exports.DEFAULT_ROLE_PERMISSIONS = void 0;
var roles_1 = require("./roles");
Object.defineProperty(exports, "DEFAULT_ROLE_PERMISSIONS", { enumerable: true, get: function () { return roles_1.DEFAULT_ROLE_PERMISSIONS; } });
Object.defineProperty(exports, "ROLE_HIERARCHY", { enumerable: true, get: function () { return roles_1.ROLE_HIERARCHY; } });
var limits_1 = require("./limits");
Object.defineProperty(exports, "MAX_MESSAGE_LENGTH", { enumerable: true, get: function () { return limits_1.MAX_MESSAGE_LENGTH; } });
Object.defineProperty(exports, "MAX_FILE_SIZE_BYTES", { enumerable: true, get: function () { return limits_1.MAX_FILE_SIZE_BYTES; } });
Object.defineProperty(exports, "MAX_FILE_SIZE_GUEST_BYTES", { enumerable: true, get: function () { return limits_1.MAX_FILE_SIZE_GUEST_BYTES; } });
Object.defineProperty(exports, "MAX_GROUP_MEMBERS", { enumerable: true, get: function () { return limits_1.MAX_GROUP_MEMBERS; } });
Object.defineProperty(exports, "MAX_CHANNEL_MEMBERS", { enumerable: true, get: function () { return limits_1.MAX_CHANNEL_MEMBERS; } });
Object.defineProperty(exports, "MAX_ORGS_PER_USER", { enumerable: true, get: function () { return limits_1.MAX_ORGS_PER_USER; } });
Object.defineProperty(exports, "MAX_CHATS_PER_PAGE", { enumerable: true, get: function () { return limits_1.MAX_CHATS_PER_PAGE; } });
Object.defineProperty(exports, "MAX_MESSAGES_PER_PAGE", { enumerable: true, get: function () { return limits_1.MAX_MESSAGES_PER_PAGE; } });
Object.defineProperty(exports, "MAX_SEARCH_RESULTS", { enumerable: true, get: function () { return limits_1.MAX_SEARCH_RESULTS; } });
Object.defineProperty(exports, "MAX_REACTIONS_PER_MESSAGE", { enumerable: true, get: function () { return limits_1.MAX_REACTIONS_PER_MESSAGE; } });
Object.defineProperty(exports, "MAX_PINNED_MESSAGES", { enumerable: true, get: function () { return limits_1.MAX_PINNED_MESSAGES; } });
Object.defineProperty(exports, "MAX_FILE_ATTACHMENTS_PER_MESSAGE", { enumerable: true, get: function () { return limits_1.MAX_FILE_ATTACHMENTS_PER_MESSAGE; } });
Object.defineProperty(exports, "MAX_TASK_WATCHERS", { enumerable: true, get: function () { return limits_1.MAX_TASK_WATCHERS; } });
Object.defineProperty(exports, "MESSAGE_EDIT_WINDOW_MS", { enumerable: true, get: function () { return limits_1.MESSAGE_EDIT_WINDOW_MS; } });
Object.defineProperty(exports, "TYPING_INDICATOR_TIMEOUT_MS", { enumerable: true, get: function () { return limits_1.TYPING_INDICATOR_TIMEOUT_MS; } });
Object.defineProperty(exports, "PRESENCE_OFFLINE_THRESHOLD_MS", { enumerable: true, get: function () { return limits_1.PRESENCE_OFFLINE_THRESHOLD_MS; } });
Object.defineProperty(exports, "INVITE_EXPIRY_HOURS", { enumerable: true, get: function () { return limits_1.INVITE_EXPIRY_HOURS; } });
Object.defineProperty(exports, "REFRESH_TOKEN_MAX_SESSIONS", { enumerable: true, get: function () { return limits_1.REFRESH_TOKEN_MAX_SESSIONS; } });
var events_1 = require("./events");
Object.defineProperty(exports, "WS_EVENTS", { enumerable: true, get: function () { return events_1.WS_EVENTS; } });
var mime_types_1 = require("./mime-types");
Object.defineProperty(exports, "ALLOWED_IMAGE_TYPES", { enumerable: true, get: function () { return mime_types_1.ALLOWED_IMAGE_TYPES; } });
Object.defineProperty(exports, "ALLOWED_VIDEO_TYPES", { enumerable: true, get: function () { return mime_types_1.ALLOWED_VIDEO_TYPES; } });
Object.defineProperty(exports, "ALLOWED_AUDIO_TYPES", { enumerable: true, get: function () { return mime_types_1.ALLOWED_AUDIO_TYPES; } });
Object.defineProperty(exports, "ALLOWED_DOCUMENT_TYPES", { enumerable: true, get: function () { return mime_types_1.ALLOWED_DOCUMENT_TYPES; } });
Object.defineProperty(exports, "ALLOWED_ARCHIVE_TYPES", { enumerable: true, get: function () { return mime_types_1.ALLOWED_ARCHIVE_TYPES; } });
Object.defineProperty(exports, "ALL_ALLOWED_TYPES", { enumerable: true, get: function () { return mime_types_1.ALL_ALLOWED_TYPES; } });
Object.defineProperty(exports, "getFileCategory", { enumerable: true, get: function () { return mime_types_1.getFileCategory; } });
var regex_1 = require("./regex");
Object.defineProperty(exports, "EMAIL_REGEX", { enumerable: true, get: function () { return regex_1.EMAIL_REGEX; } });
Object.defineProperty(exports, "PHONE_E164_REGEX", { enumerable: true, get: function () { return regex_1.PHONE_E164_REGEX; } });
Object.defineProperty(exports, "SLUG_REGEX", { enumerable: true, get: function () { return regex_1.SLUG_REGEX; } });
Object.defineProperty(exports, "MENTION_REGEX", { enumerable: true, get: function () { return regex_1.MENTION_REGEX; } });
Object.defineProperty(exports, "CHANNEL_MENTION_REGEX", { enumerable: true, get: function () { return regex_1.CHANNEL_MENTION_REGEX; } });
Object.defineProperty(exports, "URL_REGEX", { enumerable: true, get: function () { return regex_1.URL_REGEX; } });
Object.defineProperty(exports, "STRONG_PASSWORD_REGEX", { enumerable: true, get: function () { return regex_1.STRONG_PASSWORD_REGEX; } });
//# sourceMappingURL=index.js.map