"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.REFRESH_TOKEN_MAX_SESSIONS = exports.INVITE_EXPIRY_HOURS = exports.PRESENCE_OFFLINE_THRESHOLD_MS = exports.TYPING_INDICATOR_TIMEOUT_MS = exports.MESSAGE_EDIT_WINDOW_MS = exports.MAX_TASK_WATCHERS = exports.MAX_FILE_ATTACHMENTS_PER_MESSAGE = exports.MAX_PINNED_MESSAGES = exports.MAX_REACTIONS_PER_MESSAGE = exports.MAX_SEARCH_RESULTS = exports.MAX_MESSAGES_PER_PAGE = exports.MAX_CHATS_PER_PAGE = exports.MAX_ORGS_PER_USER = exports.MAX_CHANNEL_MEMBERS = exports.MAX_GROUP_MEMBERS = exports.MAX_FILE_SIZE_GUEST_BYTES = exports.MAX_FILE_SIZE_BYTES = exports.MAX_MESSAGE_LENGTH = void 0;
exports.MAX_MESSAGE_LENGTH = 4096;
exports.MAX_FILE_SIZE_BYTES = 52428800; // 50MB
exports.MAX_FILE_SIZE_GUEST_BYTES = 10485760; // 10MB
exports.MAX_GROUP_MEMBERS = 500;
exports.MAX_CHANNEL_MEMBERS = 5000;
exports.MAX_ORGS_PER_USER = 10;
exports.MAX_CHATS_PER_PAGE = 50;
exports.MAX_MESSAGES_PER_PAGE = 50;
exports.MAX_SEARCH_RESULTS = 100;
exports.MAX_REACTIONS_PER_MESSAGE = 20;
exports.MAX_PINNED_MESSAGES = 50;
exports.MAX_FILE_ATTACHMENTS_PER_MESSAGE = 10;
exports.MAX_TASK_WATCHERS = 20;
exports.MESSAGE_EDIT_WINDOW_MS = 86400000; // 24 hours
exports.TYPING_INDICATOR_TIMEOUT_MS = 3000;
exports.PRESENCE_OFFLINE_THRESHOLD_MS = 300000; // 5 minutes
exports.INVITE_EXPIRY_HOURS = 72;
exports.REFRESH_TOKEN_MAX_SESSIONS = 5;
//# sourceMappingURL=limits.js.map