type OrgRole = 'OWNER' | 'ADMIN' | 'MANAGER' | 'EMPLOYEE' | 'GUEST';

type Permission =
  | 'CHAT_CREATE'
  | 'CHAT_MANAGE_MEMBERS'
  | 'MESSAGE_DELETE_OWN'
  | 'MESSAGE_DELETE_ANY'
  | 'MESSAGE_EDIT_OWN'
  | 'MESSAGE_PIN'
  | 'FILE_UPLOAD'
  | 'FILE_DELETE_OWN'
  | 'FILE_DELETE_ANY'
  | 'TASK_CREATE'
  | 'TASK_ASSIGN'
  | 'TASK_DELETE'
  | 'MEMBER_INVITE'
  | 'MEMBER_REMOVE'
  | 'MEMBER_CHANGE_ROLE'
  | 'CALL_INITIATE'
  | 'CALL_MANAGE'
  | 'CHANNEL_CREATE'
  | 'CHANNEL_DELETE'
  | 'VIEW_ALL_MEMBERS'
  | 'DEPARTMENT_MANAGE'
  | 'ORG_SETTINGS'
  | 'ORG_DELETE';

const ALL_PERMISSIONS: Permission[] = [
  'CHAT_CREATE',
  'CHAT_MANAGE_MEMBERS',
  'MESSAGE_DELETE_OWN',
  'MESSAGE_DELETE_ANY',
  'MESSAGE_EDIT_OWN',
  'MESSAGE_PIN',
  'FILE_UPLOAD',
  'FILE_DELETE_OWN',
  'FILE_DELETE_ANY',
  'TASK_CREATE',
  'TASK_ASSIGN',
  'TASK_DELETE',
  'MEMBER_INVITE',
  'MEMBER_REMOVE',
  'MEMBER_CHANGE_ROLE',
  'CALL_INITIATE',
  'CALL_MANAGE',
  'CHANNEL_CREATE',
  'CHANNEL_DELETE',
  'VIEW_ALL_MEMBERS',
  'DEPARTMENT_MANAGE',
  'ORG_SETTINGS',
  'ORG_DELETE',
] as const;

export const DEFAULT_ROLE_PERMISSIONS: Record<OrgRole, Permission[]> = {
  OWNER: [...ALL_PERMISSIONS],
  ADMIN: ALL_PERMISSIONS.filter((p) => p !== 'ORG_DELETE'),
  MANAGER: [
    'CHAT_CREATE',
    'CHAT_MANAGE_MEMBERS',
    'MESSAGE_DELETE_OWN',
    'MESSAGE_DELETE_ANY',
    'MESSAGE_EDIT_OWN',
    'MESSAGE_PIN',
    'FILE_UPLOAD',
    'FILE_DELETE_OWN',
    'FILE_DELETE_ANY',
    'TASK_CREATE',
    'TASK_ASSIGN',
    'TASK_DELETE',
    'MEMBER_INVITE',
    'CALL_INITIATE',
    'CALL_MANAGE',
    'CHANNEL_CREATE',
    'VIEW_ALL_MEMBERS',
    'DEPARTMENT_MANAGE',
  ],
  EMPLOYEE: [
    'CHAT_CREATE',
    'MESSAGE_DELETE_OWN',
    'MESSAGE_EDIT_OWN',
    'FILE_UPLOAD',
    'FILE_DELETE_OWN',
    'TASK_CREATE',
    'CALL_INITIATE',
    'VIEW_ALL_MEMBERS',
  ],
  GUEST: [
    'MESSAGE_EDIT_OWN',
    'FILE_UPLOAD',
    'FILE_DELETE_OWN',
  ],
} as const;

export const ROLE_HIERARCHY: Record<string, number> = {
  OWNER: 5,
  ADMIN: 4,
  MANAGER: 3,
  EMPLOYEE: 2,
  GUEST: 1,
} as const;
